---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_epaper
    cmake-args: -DEXTRA_CONF_FILE=../../config/left-peripheral.conf

  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_epaper
    cmake-args: -DEXTRA_CONF_FILE=../../config/right-central.conf
